export const variables = {
  panelItems: [
    {
      adult: false,
      backdrop_path: "/cjEcqdRdPQJhYre3HUAc5538Gk8.jpg",
      genre_ids: [28, 14, 35],
      id: 845781,
      original_language: "en",
      original_title: "Red One",
      overview:
        "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.",
      popularity: 6741.399,
      poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
      release_date: "2024-10-31",
      title: "Red One",
      video: false,
      vote_average: 7,
      vote_count: 974,
    },
    {
      adult: false,
      backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
      genre_ids: [16, 12, 10751, 35],
      id: 1241982,
      original_language: "en",
      original_title: "Moana 2",
      overview:
        "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      popularity: 2865.481,
      poster_path: "/khwDcPYD5xo6B8404mGGe6pYWtI.jpg",
      release_date: "2024-11-21",
      title: "Moana 2",
      video: false,
      vote_average: 7,
      vote_count: 532,
    },
    {
      adult: false,
      backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
      genre_ids: [28, 878, 53],
      id: 1035048,
      original_language: "en",
      original_title: "Elevation",
      overview: "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
      popularity: 1626.093,
      poster_path: "/uQhYBxOVFU6s9agD49FnGHwJqG5.jpg",
      release_date: "2024-11-07",
      title: "Elevation",
      video: false,
      vote_average: 6.4,
      vote_count: 176,
    },
    {
      adult: false,
      backdrop_path: "/hT2yA8oaKVjXHjPWlmy08fdPz9p.jpg",
      genre_ids: [12, 10751, 18, 16],
      id: 762509,
      original_language: "en",
      original_title: "Mufasa: The Lion King",
      overview:
        "Told in flashbacks, Mufasa is an orphaned cub, lost and alone until he meets a sympathetic lion named Taka—the heir to a royal bloodline. The chance meeting sets in motion a journey of misfits searching for their destiny and working together to evade a threatening and deadly foe.",
      popularity: 1653.939,
      poster_path: "/lurEK87kukWNaHd0zYnsi3yzJrs.jpg",
      release_date: "2024-12-18",
      title: "Mufasa: The Lion King",
      video: false,
      vote_average: 6.8,
      vote_count: 39,
    },
    {
      adult: false,
      backdrop_path: "/6lE2e6j8qbtQR8aHxQNJlwxdmKV.jpg",
      genre_ids: [28, 80, 53],
      id: 974453,
      original_language: "en",
      original_title: "Absolution",
      overview:
        "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
      popularity: 1211.189,
      poster_path: "/cNtAslrDhk1i3IOZ16vF7df6lMy.jpg",
      release_date: "2024-10-31",
      title: "Absolution",
      video: false,
      vote_average: 6.128,
      vote_count: 144,
    },
    {
      adult: false,
      backdrop_path: "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
      genre_ids: [27, 53],
      id: 1138194,
      original_language: "en",
      original_title: "Heretic",
      overview:
        "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
      popularity: 1042.38,
      poster_path: "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
      release_date: "2024-10-31",
      title: "Heretic",
      video: false,
      vote_average: 7.2,
      vote_count: 443,
    },
    {
      adult: false,
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      genre_ids: [878, 28, 12, 35, 10751],
      id: 939243,
      original_language: "en",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      popularity: 1126.404,
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      release_date: "2024-12-14",
      title: "Sonic the Hedgehog 3",
      video: false,
      vote_average: 7.8,
      vote_count: 16,
    },
  ],

  navOptions: [
    { label: "Home", path: "/" },
    { label: "Favourites", path: "/favourites" },
    { label: "Profile", path: "/profiles" },
  ],
};
