export const variables = {
  user: {
    avatar: {
      gravatar: {
        hash: "9a662f078ad75d1d9d49663bf793e302",
      },
      tmdb: {
        avatar_path: "/4dztY5QDPjiWj8e8YnenPV4J6SI.png",
      },
    },
    id: 100,

    username: "SteveD1972",
  },

  favouriteMovies: {
    data: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/k32XKMjmXMGeydykD32jfER3BVI.jpg",
          genre_ids: [28, 9648, 18],
          id: 1045938,
          original_language: "en",
          original_title: "G20",
          overview:
            "After the G20 Summit is overtaken by terrorists, President Danielle Sutton must bring all her statecraft and military experience to defend her family and her fellow leaders.",
          popularity: 699.255,
          poster_path: "/tSee9gbGLfqwvjoWoCQgRZ4Sfky.jpg",
          release_date: "2025-04-09",
          title: "G20",
          video: false,
          vote_average: 6.256,
          vote_count: 154,
        },
        {
          adult: false,
          backdrop_path: "/6van4BavoNXaZhCPdzLHNQ4Uc8H.jpg",
          genre_ids: [53, 28],
          id: 1087891,
          original_language: "en",
          original_title: "The Amateur",
          overview:
            "After his life is turned upside down when his wife is killed in a London terrorist attack, a brilliant but introverted CIA decoder takes matters into his own hands when his supervisors refuse to take action.",
          popularity: 117.0026,
          poster_path: "/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg",
          release_date: "2025-04-09",
          title: "The Amateur",
          video: false,
          vote_average: 6.808,
          vote_count: 86,
        },
        {
          adult: false,
          backdrop_path: "/op3qmNhvwEvyT7UFyPbIfQmKriB.jpg",
          genre_ids: [14, 12, 28],
          id: 324544,
          original_language: "en",
          original_title: "In the Lost Lands",
          overview:
            "A queen sends the powerful and feared sorceress Gray Alys to the ghostly wilderness of the Lost Lands in search of a magical power, where the sorceress and her guide, the drifter Boyce must outwit and outfight man and demon.",
          popularity: 837.1695,
          poster_path: "/iHf6bXPghWB6gT8kFkL1zo00x6X.jpg",
          release_date: "2025-02-27",
          title: "In the Lost Lands",
          video: false,
          vote_average: 6.153,
          vote_count: 121,
        },
        {
          adult: false,
          backdrop_path: "/vz14urfVNjvibJEWDAaJScxZDcZ.jpg",
          genre_ids: [10751, 35, 12, 14],
          id: 950387,
          original_language: "en",
          original_title: "A Minecraft Movie",
          overview:
            "Four misfits find themselves struggling with ordinary problems when they are suddenly pulled through a mysterious portal into the Overworld: a bizarre, cubic wonderland that thrives on imagination. To get back home, they'll have to master this world while embarking on a magical quest with an unexpected, expert crafter, Steve.",
          popularity: 695.7057,
          poster_path: "/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg",
          release_date: "2025-03-31",
          title: "A Minecraft Movie",
          video: false,
          vote_average: 6.061,
          vote_count: 502,
        },
      ],
      total_pages: 1,
      total_results: 4,
    },
  },

  favouriteTv: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/dg3OindVAGZBjlT3xYKqIAdukPL.jpg",
        genre_ids: [10765, 18, 9648],
        id: 42009,
        origin_country: ["GB"],
        original_language: "en",
        original_name: "Black Mirror",
        overview: "Twisted tales run wild in this mind-bending anthology series that reveals humanity's worst traits, greatest innovations and more.",
        popularity: 235.4729,
        poster_path: "/seN6rRfN0I6n8iDXjlSMk1QjNcq.jpg",
        first_air_date: "2011-12-04",
        name: "Black Mirror",
        vote_average: 8.3,
        vote_count: 5354,
      },
      {
        adult: false,
        backdrop_path: "/nLyXXIDMpDHvUgxchezxuhoJ4Ej.jpg",
        genre_ids: [16, 10759, 10765],
        id: 235930,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Devil May Cry",
        overview:
          "When a mysterious villain threatens to open the gates of Hell, a devilishly handsome demon hunter could be the world's best hope for salvation.",
        popularity: 91.7829,
        poster_path: "/9YA4ko7x1o2NS65lDrlKAuNAqjJ.jpg",
        first_air_date: "2025-04-03",
        name: "Devil May Cry",
        vote_average: 7.909,
        vote_count: 104,
      },
      {
        adult: false,
        backdrop_path: "/rCTLaPwuApDx8vLGjYZ9pRl7zRB.jpg",
        genre_ids: [35, 18, 9648],
        id: 111803,
        origin_country: ["US"],
        original_language: "en",
        original_name: "The White Lotus",
        overview:
          "Follow the exploits of various guests and employees at an exclusive tropical resort over the span of a week as with each passing day, a darker complexity emerges in these picture-perfect travelers, the hotel’s cheerful employees and the idyllic locale itself.",
        popularity: 132.5773,
        poster_path: "/gbSaK9v1CbcYH1ISgbM7XObD2dW.jpg",
        first_air_date: "2021-07-11",
        name: "The White Lotus",
        vote_average: 7.62,
        vote_count: 1024,
      },
      {
        adult: false,
        backdrop_path: "/vfEtEzBIn0wwWM7ppzJCGEZUSu2.jpg",
        genre_ids: [10759, 10765, 35],
        id: 229711,
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Bondsman",
        overview:
          "Backwoods bounty hunter Hub Halloran comes back from the dead with an unexpected second chance at life, love, and a nearly-forgotten musical career — only to find that his old job now has a demonic new twist.",
        popularity: 109.8843,
        poster_path: "/gwd2HpY2ymvmASUP3zMYF59IIr7.jpg",
        first_air_date: "2025-04-03",
        name: "The Bondsman",
        vote_average: 7.451,
        vote_count: 91,
      },
      {
        adult: false,
        backdrop_path: "/7dowXHcFccjmxf0YZYxDFkfVq65.jpg",
        genre_ids: [18],
        id: 100088,
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Last of Us",
        overview:
          "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
        popularity: 415.3751,
        poster_path: "/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg",
        first_air_date: "2023-01-15",
        name: "The Last of Us",
        vote_average: 8.6,
        vote_count: 5540,
      },
    ],
    total_pages: 1,
    total_results: 5,
  },
  noResults: {
    data: {
      page: 1,
      results: [],
      total_pages: 0,
      total_results: 0,
    },
  },
};
