export const variables = {
  response: {
    id: 939243,
    cast: [
      {
        adult: false,
        gender: 2,
        id: 206,
        known_for_department: "Acting",
        name: "Jim Carrey",
        original_name: "Jim Carrey",
        popularity: 19.351,
        profile_path: "/u0AqTz6Y7GHPCHINS01P7gPvDSb.jpg",
        cast_id: 15,
        character: "Ivo Robotnik / Gerald Robotnik",
        credit_id: "65982190ea37e007534d578e",
        order: 0,
      },
      {
        adult: false,
        gender: 2,
        id: 222121,
        known_for_department: "Acting",
        name: "Ben Schwartz",
        original_name: "Ben Schwartz",
        popularity: 7.988,
        profile_path: "/lJVYjPj0P6uvVxNrTy4xO2645D0.jpg",
        cast_id: 1,
        character: "Sonic (voice)",
        credit_id: "620c409e55b0c0001b919ea2",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 6384,
        known_for_department: "Acting",
        name: "Keanu Reeves",
        original_name: "Keanu Reeves",
        popularity: 32.747,
        profile_path: "/8RZLOyYGsoRe9p44q3xin9QkMHv.jpg",
        cast_id: 32,
        character: "Shadow (voice)",
        credit_id: "661d8953389da10163360621",
        order: 2,
      },
    ],
  },
};
