export const variables = {
  response: {
    data: {
      id: 939243,
      cast: [
        {
          adult: false,
          gender: 2,
          id: 206,
          known_for_department: "Acting",
          name: "Jim Carrey",
          original_name: "Jim Carrey",
          popularity: 19.351,
          profile_path: "/u0AqTz6Y7GHPCHINS01P7gPvDSb.jpg",
          cast_id: 15,
          character: "Ivo Robotnik / Gerald Robotnik",
          credit_id: "65982190ea37e007534d578e",
          order: 0,
        },
        {
          adult: false,
          gender: 2,
          id: 222121,
          known_for_department: "Acting",
          name: "Ben Schwartz",
          original_name: "Ben Schwartz",
          popularity: 7.988,
          profile_path: "/lJVYjPj0P6uvVxNrTy4xO2645D0.jpg",
          cast_id: 1,
          character: "Sonic (voice)",
          credit_id: "620c409e55b0c0001b919ea2",
          order: 1,
        },
        {
          adult: false,
          gender: 2,
          id: 6384,
          known_for_department: "Acting",
          name: "Keanu Reeves",
          original_name: "Keanu Reeves",
          popularity: 32.747,
          profile_path: "/8RZLOyYGsoRe9p44q3xin9QkMHv.jpg",
          cast_id: 32,
          character: "Shadow (voice)",
          credit_id: "661d8953389da10163360621",
          order: 2,
        },
      ],
      crew: [
        {
          adult: false,
          gender: 2,
          id: 1014026,
          known_for_department: "Writing",
          name: "Zach Dean",
          original_name: "Zach Dean",
          popularity: 5.811,
          profile_path: "/hYmQIDnJZYiFigMXuUs3NSPKtAV.jpg",
          credit_id: "62335da003bf84001c6ac12c",
          department: "Writing",
          job: "Writer",
        },
        {
          adult: false,
          gender: 2,
          id: 928106,
          known_for_department: "Writing",
          name: "C. Robert Cargill",
          original_name: "C. Robert Cargill",
          popularity: 1.252,
          profile_path: "/wU26chPT5GHacto4ILfv6QIevsu.jpg",
          credit_id: "62335dd24c1d9a007ad040c4",
          department: "Production",
          job: "Producer",
        },
        {
          adult: false,
          gender: 2,
          id: 55499,
          known_for_department: "Directing",
          name: "Scott Derrickson",
          original_name: "Scott Derrickson",
          popularity: 15.393,
          profile_path: "/nOQkRTC6OPkUHebBfjIgtiZ0hvE.jpg",
          credit_id: "62335d9734e152001cbf7002",
          department: "Directing",
          job: "Director",
        },
        {
          adult: false,
          gender: 2,
          id: 1014026,
          known_for_department: "Writing",
          name: "Zach Dean",
          original_name: "Zach Dean",
          popularity: 5.811,
          profile_path: "/hYmQIDnJZYiFigMXuUs3NSPKtAV.jpg",
          credit_id: "62335e164c1d9a0046554e9c",
          department: "Production",
          job: "Producer",
        },
      ],
    },
  },
  error: {
    message: "Network Error",
    name: "AxiosError",
    code: 404,
    status: null,
  },
  media: {
    data: {
      dates: {
        maximum: "2025-01-08",
        minimum: "2024-12-18",
      },
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
          genre_ids: [28, 878, 53],
          id: 1035048,
          original_language: "en",
          original_title: "Elevation",
          overview:
            "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
          popularity: 2146.632,
          poster_path: "/uQhYBxOVFU6s9agD49FnGHwJqG5.jpg",
          release_date: "2024-11-07",
          title: "Elevation",
          video: false,
          vote_average: 6.5,
          vote_count: 151,
        },
        {
          adult: false,
          backdrop_path: "/nOoGIymGBNtA7AEN0B6nshSEQ1p.jpg",
          genre_ids: [28, 80, 53],
          id: 974453,
          original_language: "en",
          original_title: "Absolution",
          overview:
            "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
          popularity: 1475.937,
          poster_path: "/cNtAslrDhk1i3IOZ16vF7df6lMy.jpg",
          release_date: "2024-10-31",
          title: "Absolution",
          video: false,
          vote_average: 6.1,
          vote_count: 131,
        },
        {
          adult: false,
          backdrop_path: "/1ulX4rDlS97lbDi929PUrEi507V.jpg",
          genre_ids: [28, 12, 53],
          id: 539972,
          original_language: "en",
          original_title: "Kraven the Hunter",
          overview:
            "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
          popularity: 1119.248,
          poster_path: "/i47IUSsN126K11JUzqQIOi1Mg1M.jpg",
          release_date: "2024-12-11",
          title: "Kraven the Hunter",
          video: false,
          vote_average: 5.6,
          vote_count: 54,
        },
        {
          adult: false,
          backdrop_path: "/uVlUu174iiKhsUGqnOSy46eIIMU.jpg",
          genre_ids: [18, 10749, 14],
          id: 402431,
          original_language: "en",
          original_title: "Wicked",
          overview:
            "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
          popularity: 766.652,
          poster_path: "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
          release_date: "2024-11-20",
          title: "Wicked",
          video: false,
          vote_average: 7.604,
          vote_count: 530,
        },
      ],
      total_pages: 38,
      total_results: 748,
    },
  },
};
