export const variables = {
  movies: {
    dates: {
      maximum: "2024-12-11",
      minimum: "2024-10-30",
    },
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
        genre_ids: [28, 878, 12],
        id: 912649,
        original_language: "en",
        original_title: "Venom: The Last Dance",
        overview:
          "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
        popularity: 12656.263,
        poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
        release_date: "2024-10-22",
        title: "Venom: The Last Dance",
        video: false,
        vote_average: 6.574,
        vote_count: 1120,
      },
      {
        adult: false,
        backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
        genre_ids: [16, 12, 10751, 35],
        id: 1241982,
        original_language: "en",
        original_title: "Moana 2",
        overview:
          "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
        popularity: 4485.032,
        poster_path: "/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg",
        release_date: "2024-11-21",
        title: "Moana 2",
        video: false,
        vote_average: 6.9,
        vote_count: 421,
      },
      {
        adult: false,
        backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
        genre_ids: [28, 878, 53],
        id: 1035048,
        original_language: "en",
        original_title: "Elevation",
        overview: "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
        popularity: 2554.883,
        poster_path: "/uQhYBxOVFU6s9agD49FnGHwJqG5.jpg",
        release_date: "2024-11-07",
        title: "Elevation",
        video: false,
        vote_average: 6.4,
        vote_count: 126,
      },
      {
        adult: false,
        backdrop_path: "/nOoGIymGBNtA7AEN0B6nshSEQ1p.jpg",
        genre_ids: [28, 80, 53],
        id: 974453,
        original_language: "en",
        original_title: "Absolution",
        overview:
          "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
        popularity: 1846.723,
        poster_path: "/cNtAslrDhk1i3IOZ16vF7df6lMy.jpg",
        release_date: "2024-10-31",
        title: "Absolution",
        video: false,
        vote_average: 6.1,
        vote_count: 120,
      },
      {
        adult: false,
        backdrop_path: "/m2hs6YPVrzjvRC21SE9BeXtgqFW.jpg",
        genre_ids: [16, 9648, 878, 28],
        id: 1299652,
        original_language: "en",
        original_title: "Watchmen: Chapter II",
        overview:
          "Suspicious of the events ensnaring their former colleagues, Nite Owl and Silk Spectre are spurred out of retirement to investigate. As they grapple with personal ethics, inner demons and a society turned against them, they race the clock to uncover a deepening plot that might trigger global nuclear war.",
        popularity: 1439.232,
        poster_path: "/4rBObJFpiWJOG7aIlRrOUniAkBs.jpg",
        release_date: "2024-11-25",
        title: "Watchmen: Chapter II",
        video: false,
        vote_average: 7.738,
        vote_count: 42,
      },
      {
        adult: false,
        backdrop_path: "/evFChfYeD2LqobEJf8iQsrYcGTw.jpg",
        genre_ids: [28, 80, 53],
        id: 1182387,
        original_language: "en",
        original_title: "Armor",
        overview:
          "Armored truck security guard James Brody is working with his son Casey transporting millions of dollars between banks when a team of thieves led by Rook orchestrate a takeover of their truck to seize the riches. Following a violent car chase, Rook soon has the armored truck surrounded and James and Casey find themselves cornered onto a decrepit bridge.",
        popularity: 1423.925,
        poster_path: "/685wCHwr2kyQZxvThNIM04HuuCt.jpg",
        release_date: "2024-10-30",
        title: "Armor",
        video: false,
        vote_average: 5.6,
        vote_count: 54,
      },
      {
        adult: false,
        backdrop_path: "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
        genre_ids: [28, 12, 36],
        id: 558449,
        original_language: "en",
        original_title: "Gladiator II",
        overview:
          "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
        popularity: 1262.621,
        poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
        release_date: "2024-11-05",
        title: "Gladiator II",
        video: false,
        vote_average: 6.673,
        vote_count: 1007,
      },
      {
        adult: false,
        backdrop_path: "/mQZJoIhTEkNhCYAqcHrQqhENLdu.jpg",
        genre_ids: [16, 28, 878, 10751],
        id: 1184918,
        original_language: "en",
        original_title: "The Wild Robot",
        overview:
          "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
        popularity: 1147.165,
        poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
        release_date: "2024-09-08",
        title: "The Wild Robot",
        video: false,
        vote_average: 8.4,
        vote_count: 3366,
      },
      {
        adult: false,
        backdrop_path: "/h3fwlwHotd3JfV13HdW0mxDcxPD.jpg",
        genre_ids: [35, 10749, 10770],
        id: 957119,
        original_language: "en",
        original_title: "Sidelined: The QB and Me",
        overview:
          "Dallas, a burdened but headstrong dancer, is determined to get into the best dance school in the country—her late mother’s alma mater. However, that dream is suddenly derailed when the cheeky yet secretly grieving football star, Drayton, crashes into her life with a unique story of his own. Will the two of them be able to grow into their dreams together, or will their dreams be sidelined?",
        popularity: 1338.291,
        poster_path: "/hklQwv6QVoOp5bWyh1bjuF2ydyG.jpg",
        release_date: "2024-11-29",
        title: "Sidelined: The QB and Me",
        video: false,
        vote_average: 6.6,
        vote_count: 58,
      },
      {
        adult: false,
        backdrop_path: "/cBTwQKMd7Vn6rGTGBtoFLIfj7uM.jpg",
        genre_ids: [16, 12, 28, 14],
        id: 1147416,
        original_language: "fr",
        original_title: "Miraculous World : Londres, la course contre le temps",
        overview:
          "To save the future from a terrible fate, Marinette becomes Chronobug and teams up with Bunnyx to defeat a mysterious opponent who travels through time. Who is this new supervillain, and why are they obsessed with exposing Marinette's secret superhero identity? Marinette's only hope is to defeat her new opponent to prevent the end of Ladybug and time itself!",
        popularity: 1219.844,
        poster_path: "/6AtoMpHvs9pxd30KsyK8QmJ9W9M.jpg",
        release_date: "2024-11-14",
        title: "Miraculous World, London: At the Edge of Time",
        video: false,
        vote_average: 8.7,
        vote_count: 31,
      },
      {
        adult: false,
        backdrop_path: "/2ndyL4HjM9JLMqBSgbyCM57aMWl.jpg",
        genre_ids: [27, 53],
        id: 1034541,
        original_language: "en",
        original_title: "Terrifier 3",
        overview:
          "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
        popularity: 922.731,
        poster_path: "/ju10W5gl3PPK3b7TjEmVOZap51I.jpg",
        release_date: "2024-10-09",
        title: "Terrifier 3",
        video: false,
        vote_average: 6.8,
        vote_count: 1201,
      },
      {
        adult: false,
        backdrop_path: "/uVlUu174iiKhsUGqnOSy46eIIMU.jpg",
        genre_ids: [18, 10749, 14],
        id: 402431,
        original_language: "en",
        original_title: "Wicked",
        overview:
          "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
        popularity: 1084.787,
        poster_path: "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
        release_date: "2024-11-20",
        title: "Wicked",
        video: false,
        vote_average: 7.598,
        vote_count: 486,
      },
      {
        adult: false,
        backdrop_path: "/iR79ciqhtaZ9BE7YFA1HpCHQgX4.jpg",
        genre_ids: [27, 9648],
        id: 1100782,
        original_language: "en",
        original_title: "Smile 2",
        overview:
          "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.",
        popularity: 970.057,
        poster_path: "/ht8Uv9QPv9y7K0RvUyJIaXOZTfd.jpg",
        release_date: "2024-10-16",
        title: "Smile 2",
        video: false,
        vote_average: 6.6,
        vote_count: 888,
      },
      {
        adult: false,
        backdrop_path: "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
        genre_ids: [27, 878],
        id: 933260,
        original_language: "en",
        original_title: "The Substance",
        overview:
          "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
        popularity: 900.139,
        poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
        release_date: "2024-09-07",
        title: "The Substance",
        video: false,
        vote_average: 7.3,
        vote_count: 2475,
      },
      {
        adult: false,
        backdrop_path: "/rOmUuQEZfPXglwFs5ELLLUDKodL.jpg",
        genre_ids: [28, 35, 14],
        id: 845781,
        original_language: "en",
        original_title: "Red One",
        overview:
          "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.",
        popularity: 864.206,
        poster_path: "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
        release_date: "2024-10-31",
        title: "Red One",
        video: false,
        vote_average: 6.6,
        vote_count: 227,
      },
      {
        adult: false,
        backdrop_path: "/kwXycPsLA6SV3KUOagn343TtMOf.jpg",
        genre_ids: [28, 878, 53],
        id: 791042,
        original_language: "en",
        original_title: "Levels",
        overview: "After witnessing his girlfriend's murder, a man risks everything - including reality itself - to discover the truth.",
        popularity: 792.543,
        poster_path: "/y1xm0jMIlx9Oo2a3jWNyLGm43sJ.jpg",
        release_date: "2024-11-01",
        title: "Levels",
        video: false,
        vote_average: 5.689,
        vote_count: 37,
      },
      {
        adult: false,
        backdrop_path: "/sv3clpwOSSZO1c8i9uX4zig6Lzz.jpg",
        genre_ids: [53, 80, 9648, 28],
        id: 1252470,
        original_language: "hi",
        original_title: "सिकंदर का मुकद्दर",
        overview:
          "After an unsolved diamond heist, a hard-nosed cop’s pursuit of his key suspect turns into obsession, until they finally face each other — and the truth.",
        popularity: 799.859,
        poster_path: "/eWUh4rgxtgypgnOa6uGMnUt01ux.jpg",
        release_date: "2024-11-29",
        title: "Sikandar Ka Muqaddar",
        video: false,
        vote_average: 5.4,
        vote_count: 7,
      },
      {
        adult: false,
        backdrop_path: "/liuBLPXvisMRo5w2JEKHXceWq5u.jpg",
        genre_ids: [28, 80, 18],
        id: 1171640,
        original_language: "fr",
        original_title: "GTMAX",
        overview:
          "When a notorious gang of bikers recruits her brother for a heist, a former motocross champion must face her deepest fears to keep her family safe.",
        popularity: 731.033,
        poster_path: "/bx92hl70NUhojjO3eV6LqKllj4L.jpg",
        release_date: "2024-11-19",
        title: "GTMAX",
        video: false,
        vote_average: 6.1,
        vote_count: 70,
      },
      {
        adult: false,
        backdrop_path: "/hlfu6g0h0D65SjkVhQBU20zePTl.jpg",
        genre_ids: [28, 12, 14, 16],
        id: 1357633,
        original_language: "ja",
        original_title: "俺だけレベルアップな件 -ReAwakening-",
        overview:
          "Over a decade after 'gates' connecting worlds appeared, awakening 'hunters' with superpowers, weakest hunter Sung Jinwoo encounters a double dungeon and accepts a mysterious quest, becoming the only one able to level up, changing his fate. A catch-up recap of the first season coupled with an exclusive sneak peek of the first two episodes of the highly anticipated second season in one momentous theatrical fan experience.",
        popularity: 676.182,
        poster_path: "/uzHMp5heVLR68kbbUEXFPsmxYsM.jpg",
        release_date: "2024-11-26",
        title: "Solo Leveling -ReAwakening-",
        video: false,
        vote_average: 7.9,
        vote_count: 5,
      },
      {
        adult: false,
        backdrop_path: "/n4ycOGj2tRLfINTJQ3wl0vNYqpR.jpg",
        genre_ids: [16, 14, 10751, 12, 35],
        id: 592983,
        original_language: "en",
        original_title: "Spellbound",
        overview:
          "When a powerful spell turns her parents into giant monsters, a teenage princess must journey into the wild to reverse the curse before it's too late.",
        popularity: 538.536,
        poster_path: "/xFSIygDiX70Esp9dheCgGX0Nj77.jpg",
        release_date: "2024-11-22",
        title: "Spellbound",
        video: false,
        vote_average: 6.8,
        vote_count: 135,
      },
    ],
    total_pages: 284,
    total_results: 5664,
  },
};
