export const variables = {
  movies: {
    dates: {
      maximum: "2024-12-11",
      minimum: "2024-10-30",
    },
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
        genre_ids: [28, 878, 12],
        id: 912649,
        original_language: "en",
        original_title: "Venom: The Last Dance",
        overview:
          "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
        popularity: 12656.263,
        poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
        release_date: "2024-10-22",
        title: "Venom: The Last Dance",
        video: false,
        vote_average: 6.574,
        vote_count: 1120,
      },
      {
        adult: false,
        backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
        genre_ids: [16, 12, 10751, 35],
        id: 1241982,
        original_language: "en",
        original_title: "Moana 2",
        overview:
          "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
        popularity: 4485.032,
        poster_path: "/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg",
        release_date: "2024-11-21",
        title: "Moana 2",
        video: false,
        vote_average: 6.9,
        vote_count: 421,
      },
      {
        adult: false,
        backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
        genre_ids: [28, 878, 53],
        id: 1035048,
        original_language: "en",
        original_title: "Elevation",
        overview: "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
        popularity: 2554.883,
        poster_path: "/uQhYBxOVFU6s9agD49FnGHwJqG5.jpg",
        release_date: "2024-11-07",
        title: "Elevation",
        video: false,
        vote_average: 6.4,
        vote_count: 126,
      },
    ],
    total_pages: 1,
    total_results: 3,
  },
};
