export const variables = {
  user: {
    avatar: {
      gravatar: {
        hash: "9a662f078ad75d1d9d49663bf793e302",
      },
      tmdb: {
        avatar_path: "/4dztY5QDPjiWj8e8YnenPV4J6SI.png",
      },
    },
    id: 100,

    username: "SteveD1972",
  },
  resources: [
    {
      adult: false,
      backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
      genre_ids: [28, 878, 12],
      id: 912649,
      original_language: "en",
      original_title: "Venom: The Last Dance",
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      popularity: 12656.263,
      poster_path: "/aosm8NMQ3UyoBVpSxyimorCQykC.jpg",
      release_date: "2024-10-22",
      title: "Venom: The Last Dance",
      video: false,
      vote_average: 6.574,
      vote_count: 1120,
    },
    {
      adult: false,
      backdrop_path: "/tElnmtQ6yz1PjN1kePNl8yMSb59.jpg",
      genre_ids: [16, 12, 10751, 35],
      id: 1241982,
      original_language: "en",
      original_title: "Moana 2",
      overview:
        "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      popularity: 4485.032,
      poster_path: "/yh64qw9mgXBvlaWDi7Q9tpUBAvH.jpg",
      release_date: "2024-11-21",
      title: "Moana 2",
      video: false,
      vote_average: 6.9,
      vote_count: 421,
    },
    {
      adult: false,
      backdrop_path: "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
      genre_ids: [28, 878, 53],
      id: 1035048,
      original_language: "en",
      original_title: "Elevation",
      overview: "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
      popularity: 2554.883,
      poster_path: "/uQhYBxOVFU6s9agD49FnGHwJqG5.jpg",
      release_date: "2024-11-07",
      title: "Elevation",
      video: false,
      vote_average: 6.4,
      vote_count: 126,
    },
  ],
  favourites: {
    data: {
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
          genre_ids: [10749, 878, 53],
          id: 950396,
          original_language: "en",
          original_title: "The Gorge",
          overview:
            "Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.",
          popularity: 3135.209,
          poster_path: "/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
          release_date: "2025-02-13",
          title: "The Gorge",
          video: false,
          vote_average: 7.8,
          vote_count: 1600,
        },
        {
          adult: false,
          backdrop_path: "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
          genre_ids: [12, 10751, 16],
          id: 762509,
          original_language: "en",
          original_title: "Mufasa: The Lion King",
          overview:
            "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
          popularity: 2050.558,
          poster_path: "/lurEK87kukWNaHd0zYnsi3yzJrs.jpg",
          release_date: "2024-12-18",
          title: "Mufasa: The Lion King",
          video: false,
          vote_average: 7.5,
          vote_count: 1507,
        },
        {
          adult: false,
          backdrop_path: "/gFFqWsjLjRfipKzlzaYPD097FNC.jpg",
          genre_ids: [28, 53, 80],
          id: 1126166,
          original_language: "en",
          original_title: "Flight Risk",
          overview:
            "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
          popularity: 2568.332,
          poster_path: "/q0bCG4NX32iIEsRFZqRtuvzNCyZ.jpg",
          release_date: "2025-01-22",
          title: "Flight Risk",
          video: false,
          vote_average: 6,
          vote_count: 357,
        },
        {
          adult: false,
          backdrop_path: "/zo8CIjJ2nfNOevqNajwMRO6Hwka.jpg",
          genre_ids: [16, 12, 10751, 35],
          id: 1241982,
          original_language: "en",
          original_title: "Moana 2",
          overview:
            "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
          popularity: 1861.245,
          poster_path: "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
          release_date: "2024-11-21",
          title: "Moana 2",
          video: false,
          vote_average: 7.1,
          vote_count: 1761,
        },
        {
          adult: false,
          backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
          genre_ids: [28, 878, 35, 10751],
          id: 939243,
          original_language: "en",
          original_title: "Sonic the Hedgehog 3",
          overview:
            "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
          popularity: 1976.892,
          poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
          release_date: "2024-12-19",
          title: "Sonic the Hedgehog 3",
          video: false,
          vote_average: 7.7,
          vote_count: 2047,
        },
      ],
      total_pages: 1,
      total_results: 5,
    },
  },
  error: {
    message: "Network Error",
    name: "AxiosError",
    code: 404,
    status: null,
  },
};
