export const variables = {
  resources: [
    {
      adult: false,
      backdrop_path: "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
      genre_ids: [10749, 878, 53],
      id: 950396,
      original_language: "en",
      original_title: "The Gorge",
      overview:
        "Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.",
      popularity: 1759.148,
      poster_path: "/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
      release_date: "2025-02-13",
      title: "The Gorge",
      video: false,
      vote_average: 7.8,
      vote_count: 1318,
    },
    {
      adult: false,
      backdrop_path: "/cVh8Af7a9JMOJl75ML3Dg2QVEuq.jpg",
      genre_ids: [12, 10751, 16],
      id: 762509,
      original_language: "en",
      original_title: "Mufasa: The Lion King",
      overview:
        "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      popularity: 1400.256,
      poster_path: "/9bXHaLlsFYpJUutg4E6WXAjaxDi.jpg",
      release_date: "2024-12-18",
      name: "Mufasa: The Lion King",
      video: false,
      vote_average: 7.5,
      vote_count: 1394,
    },
    {
      adult: false,
      backdrop_path: "/rOMLLMGgDgGG6XeT3P8sUdUb8nl.jpg",
      genre_ids: [28, 53, 80],
      id: 1126166,
      original_language: "en",
      original_title: "Flight Risk",
      overview:
        "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them. Watch Here : https://justwatch.pro/movie/1126166/flight-risk",
      popularity: 1072.714,
      poster_path: "/4cR3hImKd78dSs652PAkSAyJ5Cx.jpg",
      release_date: "2025-01-22",
      title: "Flight Risk",
      video: false,
      vote_average: 5.857,
      vote_count: 245,
    },
    {
      adult: false,
      backdrop_path: "/zo8CIjJ2nfNOevqNajwMRO6Hwka.jpg",
      genre_ids: [16, 12, 10751, 35],
      id: 1241982,
      original_language: "en",
      original_title: "Moana 2",
      overview:
        "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      popularity: 972.201,
      poster_path: "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
      release_date: "2024-11-21",
      title: "Moana 2",
      video: false,
      vote_average: 7.158,
      vote_count: 1698,
    },
    {
      adult: false,
      backdrop_path: "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      genre_ids: [28, 878, 35, 10751],
      id: 939243,
      original_language: "en",
      original_title: "Sonic the Hedgehog 3",
      overview:
        "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      popularity: 837.784,
      poster_path: "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      release_date: "2024-12-19",
      title: "Sonic the Hedgehog 3",
      video: false,
      vote_average: 7.8,
      vote_count: 1984,
    },
    {
      adult: false,
      backdrop_path: "/7cNE2qydew1c8fqnlhWjkE3DHc2.jpg",
      genre_ids: [28, 18, 12, 10752],
      id: 927342,
      original_language: "ta",
      original_title: "அமரன்",
      overview:
        "A heroic true story of Major Mukund Varadarajan, an Indian Army officer who displayed extraordinary bravery during a counterterrorism mission in Kashmir’s Shopian district. The film captures his courage in protecting his nation and the devotion of his wife Indhu Rebecaa Varghese.",
      popularity: 771.226,
      poster_path: "/nv5DrlFpIYIPYhwvP2wg8VjdPwl.jpg",
      release_date: "2024-10-31",
      title: "Amaran",
      video: false,
      vote_average: 7.4,
      vote_count: 165,
    },
    {
      adult: false,
      backdrop_path: "/sc1abgWNXc29wSBaerrjGBih06l.jpg",
      genre_ids: [878, 53],
      id: 1084199,
      original_language: "en",
      original_title: "Companion",
      overview:
        "During a weekend getaway at a secluded lakeside estate, a group of friends finds themselves entangled in a web of secrets, deception, and advanced technology. As tensions rise and loyalties are tested, they uncover unsettling truths about themselves and the world around them.",
      popularity: 519.134,
      poster_path: "/oCoTgC3UyWGfyQ9thE10ulWR7bn.jpg",
      release_date: "2025-01-22",
      title: "Companion",
      video: false,
      vote_average: 7,
      vote_count: 511,
    },
    {
      adult: false,
      backdrop_path: "/qfAfE5auxsuxhxPpnETRAyTP5ff.jpg",
      genre_ids: [28, 53, 878],
      id: 822119,
      original_language: "en",
      original_title: "Captain America: Brave New World",
      overview:
        "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
      popularity: 675.728,
      poster_path: "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
      release_date: "2025-02-12",
      title: "Captain America: Brave New World",
      video: false,
      vote_average: 6.2,
      vote_count: 738,
    },
  ],
};
