export const variables = {
  omdbResource: {
    Title: "The Electric State",
    Year: "2025",
    Rated: "PG-13",
    Released: "14 Mar 2025",
    Runtime: "128 min",
    Genre: "Action, Adventure, Comedy",
    Director: "Anthony Russo, Joe Russo",
    Writer: "Christopher Markus, Stephen McFeely, Simon Stålenhag",
    Actors: "Chris Pratt, Millie Bobby Brown, Woody Harrelson",
    Plot: "An orphaned teen hits the road with a mysterious robot to find her long-lost brother, teaming up with a smuggler and his wisecracking sidekick.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster: "https://m.media-amazon.com/images/M/MV5BMjQ1MTYzZmItMTkzYy00NzdmLTlhYmMtMzk5YjhiOThmZDgwXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      { Source: "Internet Movie Database", Value: "6.0/10" },
      { Source: "Metacritic", Value: "31/100" },
    ],
    Metascore: "31",
    imdbRating: "6.0",
    imdbVotes: "4,115",
    imdbID: "tt7766378",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  tmdbResource: {
    data: {
      dates: {
        maximum: "2025-03-26",
        minimum: "2025-02-12",
      },
      page: 1,
      results: [
        {
          adult: false,
          backdrop_path: "/2n7lYEeIbucsEQCswRcVB6ZYmMP.jpg",
          genre_ids: [878, 12, 18],
          id: 777443,
          original_language: "en",
          original_title: "The Electric State",
          overview:
            "An orphaned teen hits the road with a mysterious robot to find her long-lost brother, teaming up with a smuggler and his wisecracking sidekick.",
          popularity: 27.757,
          poster_path: "/jRdxyW5ZmhD3ycStlb7gwOewTuE.jpg",
          release_date: "2025-03-07",
          title: "The Electric State",
          video: false,
          vote_average: 6.772,
          vote_count: 469,
        },
        {
          adult: false,
          backdrop_path: "/2siOHQYDG7gCQB6g69g2pTZiSia.jpg",
          genre_ids: [10751, 14],
          id: 447273,
          original_language: "en",
          original_title: "Snow White",
          overview: "A princess joins forces with seven dwarfs to liberate her kingdom from her cruel stepmother, the Evil Queen.",
          popularity: 24.058,
          poster_path: "/xWWg47tTfparvjK0WJNX4xL8lW2.jpg",
          release_date: "2025-03-19",
          title: "Snow White",
          video: false,
          vote_average: 3.5,
          vote_count: 30,
        },
        {
          adult: false,
          backdrop_path: "/jmsEEwHT7GtVaYFiciKSDI4i8C1.jpg",
          genre_ids: [18],
          id: 1359893,
          original_language: "it",
          original_title: "100 di questi anni",
          overview: " ",
          popularity: 14.401,
          poster_path: "/57v4gE3Dx6TViwIe1BiC2rgghhs.jpg",
          release_date: "2025-03-17",
          title: "100 di questi anni",
          video: false,
          vote_average: 4.4,
          vote_count: 9,
        },
        {
          adult: false,
          backdrop_path: "/m4FEubjmtytpMDchQfDmbJKHOG6.jpg",
          genre_ids: [99],
          id: 1437446,
          original_language: "en",
          original_title: "The Twister: Caught in the Storm",
          overview:
            "In May 2011, a massive tornado ripped through Joplin, Missouri. With pulse-pounding firsthand footage, this documentary goes inside a deadly twister.",
          popularity: 22.729,
          poster_path: "/ggXb37lX9gW4SR7kpMaraXDFeFR.jpg",
          release_date: "2025-03-18",
          title: "The Twister: Caught in the Storm",
          video: false,
          vote_average: 7,
          vote_count: 7,
        },
      ],
      total_pages: 209,
      total_results: 4170,
    },
  },
};
